language: python

#matrix and generic is the best way to get travis to work with python & OSX
matrix:
  allow_failures:
    - os: osx
  include:
      - os: linux
        python: 3.5
      - os: linux
        python: 3.6
      - os: osx
        language: generic
        #will be python3 from homebrew
        env: PYVERSION=python3

# the old stuff
# os: 
#   - linux
#   - osx
# python:
#   - "3.5"
#   - "3.6"

notifications:
  email: never
  slack: 
    rooms: ndastrophysics:E9JMFDBpGWYdRcDneK7CTFdr
    on_success: change
    on_failure: always

# branches:
#   only:
#     - master

# get gfortran for linux builds
addons:
    apt:
        packages:
            - gfortran

# get gfortran for mac builds
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc PYVERSION; fi

install: 
  #download fsps
  - git clone https://github.com/cconroy20/fsps libfsps
  - cd libfsps/src
  # replace with a travis specific makefile
  # thanks to https://github.com/dfm/python-fsps/blob/master/.travis.yml
  - cp ../../.travis.Makefile Makefile
  - make all
  - cd ../..
  - export SPS_HOME=`pwd`/libfsps
  # install other packages
  - pip install -r requirements.txt

script: pytest -v