language: python
os: 
  - linux
  - osx

python:
  - "3.5"
  - "3.6"

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  only:
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update -qq;
      sudo apt-get install -y gfortran libblas-dev liblapack-dev;
      sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/$(gfortran -dumpversion | cut -f1,2 -d.)/libgfortran.so /usr/local/lib;
    else
      brew install gcc;
    fi

install: "pip install -r requirements.txt"
script: pytest