import numpy as np
from astropy.table import Table
import pandas as pd

# todo(This section should be a utility function)
# get_data('dataset', ['x1', 'c']) -> pd.DataFrame
# get_data_figure('name') -> np.array # this just reads in a CSV file generated by idk

# get x1
t = Table.read('data/SDSS_Photometric_SNe_Ia.fits')
salt = t['CID','X1'].to_pandas()
salt.columns = salt.columns.str.lower()
salt.rename(columns={'cid': 'SNID'}, inplace=True)
salt.set_index('SNID', inplace=True)

# get campbell_local.tsv
data_local = pd.read_csv('data/campbell_local.tsv', sep='\t', index_col='SNID')
data_local.rename(columns={'err_mu': 'hr uncert'}, inplace=True)
data_local = data_local[data_local['redshift']<0.2]  
data_local = data_local[data_local['hr']<0.7]
print(f'Original file contains {len(data_local)} lines.')

# concat is a simple way to cut salt down to the same objects as the subset of data_local
data = pd.concat([data_local, salt], axis=1)
data.dropna(inplace=True)
print(f'Combined, there is {len(data_local)} lines of data/SALT values.')

###################
DELTA_X1 = 0.22-0.16   #convert from 0.22 (photo) to 0.16 (spec)

# test to make sure things are not already changed
# SN762 has a malquest bias corrected HR of 0.15382541217564238
# SN1032 has a malquest bias corrected HR of -0.15412571647477336
if abs(data.loc[762, 'hr'] - 0.1538) > 0.0001:
    raise RuntimeError('This data appears to already be updated to the new HR')
if abs(data.loc[1032, 'hr'] + 0.1541) > 0.0001:
    raise RuntimeError('This data appears to already be updated to the new HR')
else:
    print('This data has not had its HRs updated for to use alpha = 0.16.')

# update data
print('Updating HR now.')
data['hr'] = data['hr']-DELTA_X1*data['x1']

# save data
data[list(data_local.columns.values)].to_csv('data/campbell_local_updated.tsv', sep='\t')
print('Saved data.')